export const purchaseSteps = [
  {
    id: "firstName",
    question: "What\u2019s your first name?",
    type: "text" as const,
    placeholder: "Enter your first name",
    field: "firstName",
  },
  {
    id: "lastName",
    question: "Great! And your last name?",
    type: "text" as const,
    placeholder: "Enter your last name",
    field: "lastName",
  },
  {
    id: "email",
    question: "What\u2019s the best email to reach you?",
    type: "email" as const,
    placeholder: "you@email.com",
    field: "email",
  },
  {
    id: "phone",
    question: "And a phone number so we can follow up?",
    type: "phone" as const,
    placeholder: "(919) 555-1234",
    field: "phone",
  },
  {
    id: "homeowner",
    question: "Are you currently a homeowner?",
    type: "select" as const,
    options: ["Yes", "No", "Selling my current home"],
    field: "currentHomeowner",
  },
  {
    id: "goalPayment",
    question: "What\u2019s your goal monthly mortgage payment?",
    type: "currency" as const,
    placeholder: "e.g. $2,000",
    field: "goalPayment",
  },
  {
    id: "purchaseTimeline",
    question: "When are you looking to purchase?",
    type: "select" as const,
    options: [
      "Within 30 days",
      "1\u20133 months",
      "3\u20136 months",
      "Just exploring",
    ],
    field: "timeline",
  },
  {
    id: "creditScore",
    question: "Do you have a rough idea of your credit score range?",
    type: "select" as const,
    options: ["740+", "700\u2013739", "660\u2013699", "Below 660", "Not sure"],
    field: "creditRange",
  },
];

export const refinanceSteps = [
  {
    id: "firstName",
    question: "What\u2019s your first name?",
    type: "text" as const,
    placeholder: "Enter your first name",
    field: "firstName",
  },
  {
    id: "lastName",
    question: "And your last name?",
    type: "text" as const,
    placeholder: "Enter your last name",
    field: "lastName",
  },
  {
    id: "email",
    question: "What\u2019s your email address?",
    type: "email" as const,
    placeholder: "you@email.com",
    field: "email",
  },
  {
    id: "phone",
    question: "Best phone number to reach you?",
    type: "phone" as const,
    placeholder: "(919) 555-1234",
    field: "phone",
  },
  {
    id: "currentRate",
    question: "What\u2019s your current interest rate, if you know it?",
    type: "text" as const,
    placeholder: "e.g. 6.5%",
    field: "currentRate",
  },
  {
    id: "loanBalance",
    question: "What\u2019s your approximate remaining loan balance?",
    type: "currency" as const,
    placeholder: "e.g. $250,000",
    field: "loanBalance",
  },
  {
    id: "refiGoal",
    question: "What\u2019s your main goal for refinancing?",
    type: "select" as const,
    options: [
      "Lower monthly payment",
      "Cash out equity",
      "Shorter loan term",
      "Remove mortgage insurance",
    ],
    field: "refiGoal",
  },
  {
    id: "goalPayment",
    question: "What would be your ideal monthly payment?",
    type: "currency" as const,
    placeholder: "e.g. $1,500",
    field: "goalPayment",
  },
];

export const dpaSteps = [
  {
    id: "firstName",
    question: "What\u2019s your first name?",
    type: "text" as const,
    placeholder: "Enter your first name",
    field: "firstName",
  },
  {
    id: "lastName",
    question: "And your last name?",
    type: "text" as const,
    placeholder: "Enter your last name",
    field: "lastName",
  },
  {
    id: "email",
    question: "What\u2019s your email address?",
    type: "email" as const,
    placeholder: "you@email.com",
    field: "email",
  },
  {
    id: "phone",
    question: "What\u2019s a good number to call you?",
    type: "phone" as const,
    placeholder: "(919) 555-1234",
    field: "phone",
  },
  {
    id: "firstTimeBuyer",
    question: "Are you a first-time home buyer?",
    type: "select" as const,
    options: ["Yes", "No", "Not sure if I qualify"],
    field: "firstTimeBuyer",
  },
  {
    id: "income",
    question: "What\u2019s your approximate household income?",
    type: "currency" as const,
    placeholder: "e.g. $65,000",
    field: "householdIncome",
  },
  {
    id: "goalPayment",
    question: "What monthly payment are you comfortable with?",
    type: "currency" as const,
    placeholder: "e.g. $1,500",
    field: "goalPayment",
  },
  {
    id: "creditScore",
    question: "Any idea of your credit score range?",
    type: "select" as const,
    options: ["740+", "700\u2013739", "660\u2013699", "Below 660", "Not sure"],
    field: "creditRange",
  },
];

export const investorSteps = [
  {
    id: "firstName",
    question: "What\u2019s your first name?",
    type: "text" as const,
    placeholder: "Enter your first name",
    field: "firstName",
  },
  {
    id: "lastName",
    question: "And your last name?",
    type: "text" as const,
    placeholder: "Enter your last name",
    field: "lastName",
  },
  {
    id: "email",
    question: "Your email address?",
    type: "email" as const,
    placeholder: "you@email.com",
    field: "email",
  },
  {
    id: "phone",
    question: "Best phone number to reach you?",
    type: "phone" as const,
    placeholder: "(919) 555-1234",
    field: "phone",
  },
  {
    id: "properties",
    question: "How many investment properties do you currently own?",
    type: "select" as const,
    options: ["0 \u2013 first investment", "1\u20134", "5\u201310", "10+"],
    field: "propertiesOwned",
  },
  {
    id: "strategy",
    question: "What\u2019s your investment strategy?",
    type: "select" as const,
    options: [
      "Buy and hold",
      "Fix and flip",
      "Short-term rental",
      "Multi-family",
    ],
    field: "investmentStrategy",
  },
  {
    id: "purchasePrice",
    question: "What purchase price range are you targeting?",
    type: "currency" as const,
    placeholder: "e.g. $350,000",
    field: "targetPrice",
  },
  {
    id: "timeline",
    question: "When do you plan to make your next purchase?",
    type: "select" as const,
    options: [
      "Within 30 days",
      "1\u20133 months",
      "3\u20136 months",
      "Just researching",
    ],
    field: "timeline",
  },
];

export const newConstructionSteps = [
  {
    id: "firstName",
    question: "What\u2019s your first name?",
    type: "text" as const,
    placeholder: "Enter your first name",
    field: "firstName",
  },
  {
    id: "lastName",
    question: "And your last name?",
    type: "text" as const,
    placeholder: "Enter your last name",
    field: "lastName",
  },
  {
    id: "email",
    question: "What\u2019s your email address?",
    type: "email" as const,
    placeholder: "you@email.com",
    field: "email",
  },
  {
    id: "phone",
    question: "What\u2019s the best number to reach you?",
    type: "phone" as const,
    placeholder: "(919) 555-1234",
    field: "phone",
  },
  {
    id: "hasBuilder",
    question: "Have you already selected a builder or community?",
    type: "select" as const,
    options: [
      "Yes, I have a builder",
      "Still looking",
      "Building on my own lot",
    ],
    field: "hasBuilder",
  },
  {
    id: "currentHomeowner",
    question: "Are you currently a homeowner?",
    type: "select" as const,
    options: ["Yes", "No"],
    field: "currentHomeowner",
  },
  {
    id: "budget",
    question: "What\u2019s your target budget for the new build?",
    type: "currency" as const,
    placeholder: "e.g. $450,000",
    field: "budget",
  },
  {
    id: "goalPayment",
    question: "What monthly payment would work best for you?",
    type: "currency" as const,
    placeholder: "e.g. $2,500",
    field: "goalPayment",
  },
];
